version: "2"
volumes:
  world:
  world_nether:
  world_the_ends:
  dynmap:
services:
  server:
    build: .
    ports:
      - 25565:25565
      - 8123:8123
    stop_signal: SIGINT
    depends_on:
      - notify
    volumes:
      - world:/data/world
      - world_nether:/data/world_nether
      - world_the_ends:/data/world_the_end
      - dynmap:/data/plugins/dynmap/web/tiles/world
    env_file: .env
    logging:
      driver: "fluentd"
    restart: on-failure[5]

  backup:
    image: quay.io/spesnova/dockup:latest
    volumes:
      - world:/data/world:ro
      - world_nether:/data/world_nether:ro
      - world_the_ends:/data/world_the_end:ro
      - dynmap:/data/plugins/dynmap/web/tiles/world:ro
    env_file: .env

  restore:
    image: quay.io/spesnova/dockup:latest
    command: restore
    volumes:
      - world:/data/world
      - world_nether:/data/world_nether
      - world_the_ends:/data/world_the_end
      - dynmap:/data/plugins/dynmap/web/tiles/world
    env_file: .env

  notify:
    build:
      context: ./notify
      dockerfile: Dockerfile
    ports:
      - 24224:24224
    env_file: .env
