# Minecraft Server
server:
  image: quay.io/spesnova/minecraft:latest
  ports:
    - 27364:25565
  volumes_from:
    - worlds
  volumes:
    - /data/world
    - /data/world_nether
    - /data/world_the_end
  env_file: .env

worlds:
  command: /bin/sh
  image: alpine:3.2
  volumes:
    - /data/world
    - /data/world_nether
    - /data/world_the_end

backup:
  image: quay.io/spesnova/dockup:latest
  volumes_from:
    - worlds
  env_file: .env
  environment:
    - RESTORE=false

restore:
  image: quay.io/spesnova/dockup:latest
  volumes_from:
    - worlds
  env_file: .env
  environment:
    - RESTORE=true
