# Minecraft Server
server:
  build: .
  ports:
    - 25565:25565
  volumes_from:
    - worlds
  volumes:
    - /data/world
    - /data/world_nether
    - /data/world_the_end
  env_file: .env
  log_driver: "fluentd"
  restart: on-failure[5]

worlds:
  command: /bin/sh
  image: alpine:3.2
  volumes:
    - /data/world
    - /data/world_nether
    - /data/world_the_end

backup:
  image: quay.io/spesnova/dockup:latest
  volumes_from:
    - worlds
  env_file: .env
  environment:
    - RESTORE=false

restore:
  image: quay.io/spesnova/dockup:latest
  volumes_from:
    - worlds
  env_file: .env
  environment:
    - RESTORE=true

notify:
  build: notify
  dockerfile: Dockerfile
  ports:
    - 24224:24224
  env_file: .env
