# Minecraft Server
server:
  build: .
  ports:
    - 25565:25565
  volumes:
    - /data/world
    - /data/world_nether
    - /data/world_the_end
  volumes_from:
    - restore
  log_driver: "fluentd"
notify:
  build: notify
  dockerfile: Dockerfile
  ports:
    - 24224:24224
  env_file: .env
  environment:
    - SLACK_CHANNEL=minecraft
    - SLACK_USERNAME=Minecraft Server
    - SLACK_ICON_EMOJI=minecraft
backup:
  image: quay.io/spesnova/dockup:latest
  volumes_from:
    - server
  env_file: .env
  environment:
    - BACKUP_NAME=worlds
    - PATHS_TO_BACKUP=/data/world /data/world_nether /data/world_the_end
    - CRON_TIME=3 0-23/3 * * *
restore:
  image: quay.io/spesnova/dockup:latest
  volumes:
    - /data/world
    - /data/world_nether
    - /data/world_the_end
  env_file: .env
  environment:
    - BACKUP_NAME=worlds
    - PATHS_TO_BACKUP=/data/world /data/world_nether /data/world_the_end
    - RESTORE=true
