# Minecraft Server
server:
  image: quay.io/spesnova/minecraft:latest
  ports:
    - 27364:25565
  volumes:
    - ~/minecraft_data/world:/data/world
    - ~/minecraft_data/world_nether:/data/world_nether
    - ~/minecraft_data/world_the_end:/data/world_the_end
  env_file: .env
