version: "2"
volumes:
  world:
  world_nether:
  world_the_ends:
  dynmap:
services:
  server:
    image: quay.io/spesnova/minecraft:latest
    ports:
      - 27364:25565
      - 9321:8123
    volumes:
      - world:/data/world
      - world_nether:/data/world_nether
      - world_the_ends:/data/world_the_end
      - dynmap:/data/plugins/dynmap/web/tiles/world
    env_file: .env
    logging:
      driver: "fluentd"
    restart: on-failure[5]

  backup:
    image: quay.io/spesnova/dockup:latest
    volumes:
      - world:/data/world:ro
      - world_nether:/data/world_nether:ro
      - world_the_ends:/data/world_the_end:ro
      - dynmap:/data/plugins/dynmap/web/tiles/world:ro
    env_file: .env

  restore:
    image: quay.io/spesnova/dockup:latest
    command: restore
    volumes:
      - world:/data/world
      - world_nether:/data/world_nether
      - world_the_ends:/data/world_the_end
      - dynmap:/data/plugins/dynmap/web/tiles/world
    env_file: .env

  notify:
    image: quay.io/spesnova/minecraft-notify:latest
    ports:
      - 24224:24224
    env_file: .env

  monitor:
    image: datadog/docker-dd-agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    env_file: .env
    hostname: minecraft-server
